# -*- coding: utf-8 -*-
"""REcurent_N_1

Automatically generated by Colab.



# -*- coding: utf-8 -*-


Recurrent Signal Denoising Network (SLE-RNN)
=============================================

A recurrent neural network for iterative signal recovery.
At each iteration, the clean signal is separated from the noisy signal and
only the reconstructed signal is passed to the next iteration.

Mathematical model:
    Y^(0) = Y_noisy (input)
    S^(t) = Filter(Y^(t-1); α, κ, r)  (spectral reconstruction)
    Y^(t) = S^(t)                     (noise-free, only reconstructed signal)
    result: S^(T) (after T iterations)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import math
import random
from typing import List, Tuple, Optional, Callable
from dataclasses import dataclass
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt

# =============================================================================
# 1. CONFIGURATION AND HELPER CLASSES
# =============================================================================

@dataclass
class ModelConfig:
    """Model configuration"""
    M: int = 300                    # Signal length
    T: int = 1                        # Time interval [0, T]
    epsilon: float = 0.01             # Noise level
    num_iterations: int = 3           # Number of recurrent iterations

    # Gating network architecture
    gating_hidden: int = 64

    # Training parameters
    batch_size: int = 64
    epochs: int = 10
    lr: float = 1e-2


@dataclass
class ParameterGrid:
    """Stores the grid of adaptive parameters"""
    alphas: List[float]
    kappas: List[float]
    rs: List[float]

    def __len__(self) -> int:
        return len(self.alphas) * len(self.kappas) * len(self.rs)

    def get_all_combinations(self) -> List[Tuple[float, float, float]]:
        """Returns all (alpha, kappa, r) combinations"""
        import itertools
        return list(itertools.product(self.alphas, self.kappas, self.rs))


# =============================================================================
# 2. SIGNAL GENERATORS
# =============================================================================

class SignalGenerators:
    """Various signal functions"""

    @staticmethod
    def sinusoidal(t: np.ndarray) -> np.ndarray:
        """Sinusoidal signal: A*sin(2πft + φ)"""
        A = random.uniform(0.5, 1.0)
        f = random.uniform(0.1, 1.0)
        phi = random.uniform(0, 2 * np.pi)
        return A * np.sin(2 * np.pi * t)

    @staticmethod
    def square_wave(t: np.ndarray) -> np.ndarray:
        """Square wave signal: A*sign(sin(2πt + φ))"""
        A = random.uniform(0.1, 2.0)
        phi = random.uniform(0, 2 * np.pi)
        s = A * np.sign(np.sin(2 * np.pi * t + phi))
        s[-1] = 0  # Set last point to 0
        return s

    @staticmethod
    def sawtooth(t: np.ndarray) -> np.ndarray:
        """Sawtooth signal: A*(t - floor(t + 0.5))"""
        A = random.uniform(0.1, 2.0)
        return A * (t - np.floor(t + 0.5))

    @staticmethod
    def triangular(t: np.ndarray) -> np.ndarray:
        """Triangular signal: A*|2(t - floor(t + 0.5))|"""
        A = random.uniform(0.3, 1.0)
        return A * np.abs(2 * (t - np.floor(t + 0.5)))

    @staticmethod
    def damped_oscillation(t: np.ndarray) -> np.ndarray:
        """Damped oscillation: A*exp(-αt)*sin(2πft)"""
        A = random.uniform(0.5, 2.0)
        alpha = random.uniform(1.0, 5.0)
        f = random.uniform(1.0, 5.0)
        return A * np.exp(-alpha * t) * np.sin(2 * np.pi * f * t)

    @staticmethod
    def gaussian_pulse(t: np.ndarray) -> np.ndarray:
        """Gaussian pulse: A*exp(-(t-μ)²/(2σ²))"""
        A = random.uniform(0.5, 2.0)
        mu = random.uniform(0.3, 0.7)
        sigma = random.uniform(0.05, 0.2)
        return A * np.exp(-(t - mu)**2 / (2 * sigma**2))

    @staticmethod
    def chirp(t: np.ndarray) -> np.ndarray:
        """Chirp signal: A*sin(2π(f₀t + (k/2)t²))"""
        A = random.uniform(0.5, 2.0)
        f0 = random.uniform(1.0, 5.0)
        k = random.uniform(1.0, 4.0)
        return A * np.sin(2 * np.pi * (f0 * t + (k / 2) * t**2))

    @staticmethod
    def single_pulse(t: np.ndarray) -> np.ndarray:
        """Single pulse"""
        pulse_width = random.uniform(0.05, 0.2)
        t_start = random.uniform(0, 1 - pulse_width)
        signal = np.zeros_like(t)
        signal[(t >= t_start) & (t < t_start + pulse_width)] = 1.0
        return signal

    @classmethod
    def get_all_generators(cls) -> List[Callable]:
        """Returns all generators"""
        return [
            cls.sinusoidal,
            cls.square_wave,
            cls.sawtooth,
            cls.triangular,
            cls.damped_oscillation,
            cls.gaussian_pulse,
            cls.chirp,
            cls.single_pulse
        ]


# =============================================================================
# 3. DATA GENERATION
# =============================================================================

class SignalDatasetGenerator:
    """Generates noisy and clean signal pairs"""

    def __init__(self, config: ModelConfig):
        self.config = config
        self.generators = SignalGenerators.get_all_generators()

    def generate_noisy_signals(
        self,
        n_samples: int,
        noise_eps: Optional[float] = None
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Generates noisy data for different signal types

        Args:
            n_samples: Number of samples per signal type
            noise_eps: Noise strength (uses config.epsilon if None)

        Returns:
            (noisy_signals, clean_signals) - shape: (n_samples * 8 * 5, M)
        """
        if noise_eps is None:
            noise_eps = self.config.epsilon

        M = self.config.M
        t = np.linspace(0, self.config.T, M)

        clean_signals = []
        noisy_signals = []

        # For each signal type
        for generator in self.generators:
            for _ in range(n_samples):
                # Clean signal
                S = generator(t)

                # 5 different noisy realizations
                for _ in range(5):
                    # Additive White Gaussian Noise (AWGN)
                    noise = noise_eps * np.random.normal(0, 1, size=M)
                    Y = S + noise

                    clean_signals.append(S)
                    noisy_signals.append(Y)

        return (
            np.array(noisy_signals, dtype=np.float32),
            np.array(clean_signals, dtype=np.float32)
        )

    def generate_single_type(
        self,
        n_samples: int,
        signal_type: int,
        noise_eps: Optional[float] = None
    ) -> Tuple[np.ndarray, np.ndarray, str]:
        """
        Generates a single signal type

        Args:
            n_samples: Number of samples
            signal_type: 0-7 (sinusoidal, square, sawtooth, ...)
            noise_eps: Noise strength

        Returns:
            (noisy, clean, signal_name)
        """
        if noise_eps is None:
            noise_eps = self.config.epsilon

        M = self.config.M
        t = np.linspace(0, self.config.T, M)

        generators = self.generators
        signal_names = [
            "Sinusoidal", "Square wave", "Sawtooth", "Triangular",
            "Damped oscillation", "Gaussian Pulse", "Chirp", "Single pulse"
        ]

        if signal_type < 0 or signal_type >= len(generators):
            raise ValueError(f"signal_type must be between 0 and {len(generators)-1}")

        S = generators[signal_type](t)
        name = signal_names[signal_type]

        clean = []
        noisy = []

        for _ in range(n_samples):
            noise = noise_eps * np.random.normal(0, 1, size=M)
            Y = S + noise

            clean.append(S)
            noisy.append(Y)

        return (
            np.array(noisy, dtype=np.float32),
            np.array(clean, dtype=np.float32),
            name
        )


class SignalDataset(Dataset):
    """PyTorch Dataset wrapper"""

    def __init__(self, noisy: np.ndarray, clean: np.ndarray):
        self.noisy = torch.from_numpy(noisy)
        self.clean = torch.from_numpy(clean)

    def __len__(self) -> int:
        return len(self.noisy)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.noisy[idx], self.clean[idx]


# =============================================================================
# 4. SPECTRAL RECONSTRUCTION CORE
# =============================================================================

class SpectralReconstructor(nn.Module):
    """
    Signal reconstruction using spectral basis functions

    Trigonometric basis:
        φ_{2k}(t) = √2 * sin(2πkt)
        φ_{2k+1}(t) = √2 * cos(2πkt)
    """

    def __init__(self, max_basis: int, T: float = 1.0):
        super().__init__()
        self.max_basis = max_basis
        self.T = T

        # Precompute time grid
        self.register_buffer('t_grid', None)
        self.register_buffer('basis_cache', None)

    def _get_phi_matrix1(self, j_vals: torch.Tensor, t_vals: torch.Tensor) -> torch.Tensor:
        """
        Creates trigonometric basis matrix

        Args:
            j_vals: Basis indices (1, 2, ..., l)
            t_vals: Time points [0, T]

        Returns:
            phi: (l, M) basis matrix
        """
        # floor division by 2 for sin/cos
        j_half = torch.floor(j_vals / 2)

        # Angles: 2π * (j//2) * t
        angles = 2 * math.pi * torch.tensordot(j_half, t_vals, dims=0)

        # Even indices -> sin, odd indices -> cos
        is_even = ((j_vals % 2) == 0).float().unsqueeze(1)

        sqrt2 = math.sqrt(2.0)
        sin_part = sqrt2 * torch.sin(angles)
        cos_part = sqrt2 * torch.cos(angles)

        phi = is_even * sin_part + (1 - is_even) * cos_part

        # Set first column to 1 (DC component)
        ones_col = torch.ones(phi.size(0), 1, device=phi.device)
        phi = torch.cat([ones_col, phi], dim=1)

        # Remove last column for correct size
        return phi[:, :-1]
    
    def _get_phi_matrix(self, j_vals: torch.Tensor, t_vals: torch.Tensor) -> torch.Tensor:
        """
        j_vals: 1, 2, ..., l  (l basis functions)
        returns: (l, M) orthonormal basis matrix
          j=1 -> phi_1 = 1 (DC)
          j=2 -> phi_2 = sqrt(2)*sin(2π·1·t)
          j=3 -> phi_3 = sqrt(2)*cos(2π·1·t)
          j=4 -> phi_4 = sqrt(2)*sin(2π·2·t)
          ...
        """
        l = j_vals.shape[0]
        M = t_vals.shape[0]
        device = t_vals.device
        sqrt2 = math.sqrt(2.0)

        # DC component (j=1)
        dc = torch.ones(1, M, device=device)   # (1, M)
        if l == 1:
            return dc

        # Remaining basis functions (j=2..l)
        j_rem = j_vals[1:]                     # (l-1,)
        k = torch.floor(j_rem / 2)             # wave number
        angles = 2 * math.pi * torch.tensordot(k, t_vals, dims=0)  # (l-1, M)

        # even j -> sin, odd j -> cos (j starts from 2)
        is_sin = ((j_rem % 2) == 0).float().unsqueeze(1)  # (l-1, 1)

        sin_part = sqrt2 * torch.sin(angles)
        cos_part = sqrt2 * torch.cos(angles)

        phi_rest = is_sin * sin_part + (1 - is_sin) * cos_part  # (l-1, M)
        phi = torch.cat([dc, phi_rest], dim=0)                  # (l, M)
        return phi

    def compute_optimal_l(
        self,
        kappa: torch.Tensor,
        alpha: torch.Tensor,
        r: torch.Tensor,
        epsilon: float,
        max_n: int
    ) -> torch.Tensor:
        """
        Computes the optimal basis length

        Condition: exp(k*l^α) * Σexp(k*m^α) - Σexp(2k*m^α) ≤ r/ε²

        Args:
            kappa: κ parameter
            alpha: α parameter
            r: r parameter
            epsilon: Noise level
            max_n: Maximum number of basis functions

        Returns:
            Optimal l (int)
        """
        device = kappa.device

        # l = 1, 2, ..., max_n
        l_range = torch.arange(1, max_n + 1, dtype=torch.float32, device=device)

        # exp(k * l^α)
        exp_kl_alpha = torch.exp(kappa * (l_range ** alpha))

        # Cumulative sums
        sum1 = torch.cumsum(exp_kl_alpha, dim=0)           # Σ exp(k*m^α)
        sum2 = torch.cumsum(torch.exp(2 * kappa * (l_range ** alpha)), dim=0)

        # Check condition
        condition = exp_kl_alpha * sum1 - sum2
        threshold = r / (epsilon ** 2)

        mask = (condition <= threshold)

        if mask.any():
            # Largest l satisfying the condition
            return (mask.nonzero(as_tuple=False).max()).int() + 1
        else:
            # If no l matches, return minimum value
            return torch.tensor(3, dtype=torch.int32, device=device)

    def forward(
        self,
        Y: torch.Tensor,
        alpha: torch.Tensor,
        kappa: torch.Tensor,
        r: torch.Tensor,
        epsilon: float
    ) -> torch.Tensor:
        """
        Signal reconstruction for a single parameter set

        Args:
            Y: (batch, M) - input signal
            alpha, kappa, r: Scalar parameters
            epsilon: Noise level

        Returns:
            S_hat: (batch, M) - reconstructed signal
        """
        batch_size, M = Y.shape
        device = Y.device

        # Optimal basis length
        l = int(self.compute_optimal_l(kappa, alpha, r, epsilon, M).item())
        l = min(l, M - 1)  # Limit

        # Time grid
        t_vals = torch.linspace(0, self.T, M, device=device)

        # Basis matrices
        j_vals = torch.arange(1, l + 1, dtype=torch.float32, device=device)
        phi_t = self._get_phi_matrix(j_vals, t_vals)  # (l, M)

        # Fourier coefficients (directly from Y)
        # omega = (1/M) * Y * φ^T
        omega = torch.matmul(Y, phi_t.T) / M  # (batch, l)

        # Tikhonov filter: λ_j = 1 - exp(-κ(l^α - j^α))
        l_float = float(l)
        j_float = j_vals  # (l,)

        lambda_j = 1.0 - torch.exp(-kappa * ((l_float ** alpha) - (j_float ** alpha)))

        # Weighted coefficients
        weighted = omega * lambda_j.unsqueeze(0)  # (batch, l)

        # Signal reconstruction
        S_hat = torch.matmul(weighted, phi_t)  # (batch, M)

        return S_hat


# =============================================================================
# 5. RECURRENT NEURAL NETWORK (MAIN MODEL)
# =============================================================================
iterationsss=[]
class RecurrentSLE(nn.Module):
    """
    Recurrent Signal Learning Engine (SLE-RNN)

    At each iteration:
        1. Compute S_hat from current Y using spectral method
        2. Pass Y_new = S_hat to next iteration (no noise added!)

    This is similar to "denoising diffusion" but deterministic.
    """

    def __init__(
        self,
        M: int,
        param_grid: ParameterGrid,
        epsilon: float,
        T: float = 1.0,
        gating_hidden: int = 64
    ):
        """
        Args:
            M: Signal length
            param_grid: (alpha, kappa, r) parameter grid
            epsilon: Noise level
            T: Time interval
            gating_hidden: Gating network hidden layer size
        """
        super().__init__()

        self.M = M
        self.epsilon = epsilon
        self.T = T
        self.param_grid = param_grid

        # All parameter combinations
        self.candidate_params = param_grid.get_all_combinations()
        self.L = len(self.candidate_params)

        print(f"Model created: {self.L} parameter combinations")

        # Reconstructor for each parameter set
        self.reconstructor = SpectralReconstructor(M, T)

        # Gating network: determines which expert (parameter) is best
        self.gating = nn.Sequential(
            nn.Linear(M, gating_hidden),
            nn.ReLU(),
            nn.Dropout(0.1),  # Regularization
            nn.Linear(gating_hidden, self.L)
        )

        # Precompute optimal l values (for speed)
        self._precompute_l_values()

    def _precompute_l_values(self):
        """Precompute optimal l for all parameters"""
        device = next(self.parameters()).device

        self.l_values = []
        for alpha, kappa, r in self.candidate_params:
            alpha_t = torch.tensor(alpha, device=device)
            kappa_t = torch.tensor(kappa, device=device)
            r_t = torch.tensor(r, device=device)

            l = self.reconstructor.compute_optimal_l(
                kappa_t, alpha_t, r_t, self.epsilon, self.M
            )
            self.l_values.append(l.item())

        self.l_values = torch.tensor(self.l_values, dtype=torch.int32)
        self.max_l = int(self.l_values.max().item())

    def _compute_single_expert(
        self,
        Y: torch.Tensor,
        idx: int
    ) -> torch.Tensor:
        """
        Reconstruction for a single expert (parameter combination)

        Args:
            Y: (batch, M) - input signal
            idx: Expert index

        Returns:
            S_hat: (batch, M) - reconstructed signal
        """
        alpha, kappa, r = self.candidate_params[idx]

        alpha_t = torch.tensor(alpha, device=Y.device, dtype=Y.dtype)
        kappa_t = torch.tensor(kappa, device=Y.device, dtype=Y.dtype)
        r_t = torch.tensor(r, device=Y.device, dtype=Y.dtype)

        return self.reconstructor(Y, alpha_t, kappa_t, r_t, self.epsilon)

    def _iterative_refinement(
        self,
        Y_initial: torch.Tensor,
        num_iterations: int
    ) -> torch.Tensor:
        """
        RECURRENT CORE — With dynamic stopping condition

        Iterative signal improvement:
            Y^(0) = Y_noisy
            for t in 1..T:
                S^(t) = Σ w_i * Expert_i(Y^(t-1))
                Y^(t) = S^(t)  <-- DIFFERENCE: no noise added!

        Stopping condition (checked after at least 2 iterations):
            MSE(S_hat_new, S_hat_old) <= (kappa^(1/alpha)) * n^(1/alpha) / n
        where kappa and alpha are from the best expert selected by gating,
        n = M (signal length).

        Maximum iterations: 10

        Args:
            Y_initial: (batch, M) - initial noisy signal
            num_iterations: (ignored, dynamic stopping is used)

        Returns:
            S_final: (batch, M) - final reconstructed signal
        """
        device = Y_initial.device
        n = float(self.M)  # Signal length (n)

        MAX_ITERATIONS = 10
        MIN_ITERATIONS = 2

        # Initial value
        Y_current = Y_initial
        S_hat_old = None  # Previous iteration result
        S_hat = None

        for iteration in range(MAX_ITERATIONS):
            # === 1. GATING: Weight of each expert ===
            logits = self.gating(Y_current)  # (batch, L)
            weights = F.softmax(logits, dim=1)  # (batch, L)

            # === 2. EXPERTS: Reconstruction for each parameter set ===
            reconstructions = []

            for idx in range(self.L):
                S_hat_i = self._compute_single_expert(Y_current, idx)
                reconstructions.append(S_hat_i)

            # Stack to (batch, L, M)
            reconstructions = torch.stack(reconstructions, dim=1)

            # === 3. AGGREGATION: Weighted average ===
            # (batch, L, 1) * (batch, L, M) -> (batch, M)
            weights_expanded = weights.unsqueeze(-1)  # (batch, L, 1)
            S_hat = (reconstructions * weights_expanded).sum(dim=1)

            # === 4. DYNAMIC STOPPING CONDITION ===
            # Check after at least 2 iterations
            if iteration >= MIN_ITERATIONS - 1 and S_hat_old is not None:
                # Find best expert index (average weight across batch)
                if iteration < 3:
                    best_expert_idx = weights.mean(dim=0).argmax().item()
                    alpha_val, kappa_val, _ = self.candidate_params[best_expert_idx]

                    # If alpha = 0 or too small, use default value
                    alpha_safe = max(alpha_val, 1e-6)

                # Threshold: (kappa^(1/alpha)) * n^(1/alpha) / n
                threshold = (kappa_val ** (1.0 / alpha_safe)) * (torch.log(torch.tensor(n)) ** (1.0 / alpha_safe)) / n

                # Batch average MSE(S_hat_new, S_hat_old)
                mse_diff = F.mse_loss(S_hat, S_hat_old).item()

                # Debug: print iteration info
                # print(f"Iter {iteration+1}: MSE_diff={mse_diff:.6f}, threshold={threshold:.6f}")

                if mse_diff <= threshold:
                    # print(f"  => Loop stopped: completed {iteration+1} iterations")
                    iterationsss.append(iteration)
                    break

            # === 5. RECURRENT UPDATE ===
            S_hat_old = S_hat.detach().clone()
            scale = Y_current.norm(dim=-1, keepdim=True) / (S_hat.norm(dim=-1, keepdim=True) + 1e-8)
            Y_current = S_hat * scale
            # Y_current = S_hat

        return Y_current

    def forward(
        self,
        Y: torch.Tensor,
        num_iterations: Optional[int] = None,
        return_all: bool = False
    ) -> torch.Tensor:
        """
        Forward pass

        Args:
            Y: (batch, M) - noisy signal(s)
            num_iterations: Maximum iterations (10 if None).
                            Dynamic stopping condition:
                            MSE(S_hat_new, S_hat_old) <= (κ^(1/α)) * n^(1/α) / n
                            At least 2 iterations are performed.
            return_all: If True, returns (S_hat, weights)

        Returns:
            S_hat: (batch, M) - reconstructed clean signal
        """
        if num_iterations is None:
            num_iterations = 10  # Maximum limit (dynamic stopping is used)

        # Recurrent iterative refinement (with dynamic stopping condition)
        S_hat = self._iterative_refinement(Y, num_iterations)

        if return_all:
            # Also return weights from the last iteration
            with torch.no_grad():
                logits = self.gating(S_hat)
                weights = F.softmax(logits, dim=1)
            return S_hat, weights

        return S_hat


# =============================================================================
# 6. PARAMETER GRID GENERATOR
# =============================================================================

def create_adaptive_param_grid(epsilon: float) -> ParameterGrid:
    """
    Creates adaptive parameter grid based on epsilon (noise level)

    Formulas:
        m_1 = 2 * (log(log(1 + 1/ε⁴)))²
        m_2 = 2 * (log(log(1 + 1/ε²)))⁴
        m_3 = 2 * (log(log(1 + 1/ε²)))²
    """
    eps = epsilon

    # Grid sizes
    m1 = 2 * int((math.log(math.log(1 + (1 / eps**4))))**2)
    m2 = 1 * int((math.log(math.log(1 + (1 / eps**2))))**4)
    m3 = 2 * int((math.log(math.log(1 + (1 / eps**2))))**2)

    print(f"Parameter grid sizes: α={m1}, κ={m2}, r={m3}")

    # Alpha values: [1/m1, 2/m1, ..., 1] / log(log(1/ε⁴))²
    denom_alpha = math.log(math.log(1 + (1 / eps**4)))**2
    alphas = [i / denom_alpha for i in range(1, m1 + 1)]

    # Kappa values
    denom_kappa = math.log(math.log(1 + (1 / eps**2)))**2
    kappas = [i / denom_kappa for i in range(1, m2 + 1)]

    # R values: 1 + [1/m3, 2/m3, ...]
    denom_r = math.log(math.log(1 + (1 / eps**2)))
    rs = [1 + i / denom_r for i in range(1, m3 + 1)]

    return ParameterGrid(alphas=alphas, kappas=kappas, rs=rs)


# =============================================================================
# 7. TRAINING AND EVALUATION
# =============================================================================

class Trainer:
    """Model training and evaluation class"""

    def __init__(
        self,
        model: RecurrentSLE,
        config: ModelConfig,
        device: torch.device
    ):
        self.model = model
        self.config = config
        self.device = device

        self.optimizer = torch.optim.Adam(model.parameters(), lr=config.lr)
        self.criterion = nn.MSELoss()

    def train(
        self,
        train_loader: DataLoader,
        epochs: Optional[int] = None
    ) -> List[float]:
        """
        Train the model

        Args:
            train_loader: DataLoader
            epochs: Number of epochs (uses config.epochs if None)

        Returns:
            losses: Average loss for each epoch
        """
        if epochs is None:
            epochs = self.config.epochs

        self.model.train()
        history = []

        for epoch in range(epochs):
            total_loss = 0.0
            num_samples = 0

            for batch_noisy, batch_clean in train_loader:
                batch_noisy = batch_noisy.to(self.device)
                batch_clean = batch_clean.to(self.device)

                self.optimizer.zero_grad()

                # Forward: recurrent iterative reconstruction
                S_hat = self.model(
                    batch_noisy,
                    num_iterations=self.config.num_iterations
                )

                # Loss: reconstructed vs true signal
                loss = self.criterion(S_hat, batch_clean)

                loss.backward()
                self.optimizer.step()

                total_loss += loss.item() * batch_noisy.size(0)
                num_samples += batch_noisy.size(0)

            avg_loss = total_loss / num_samples
            history.append(avg_loss)

            print(f"Epoch [{epoch+1}/{epochs}] - Loss: {avg_loss:.6f}")

        return history

    def evaluate(
        self,
        test_loader: DataLoader
    ) -> Tuple[float, np.ndarray, np.ndarray]:
        """
        Evaluate the model

        Returns:
            (mse, predictions, targets)
        """
        self.model.eval()
        total_mse = 0.0
        all_preds = []
        all_targets = []

        with torch.no_grad():
            for batch_noisy, batch_clean in test_loader:
                batch_noisy = batch_noisy.to(self.device)
                batch_clean = batch_clean.to(self.device)

                S_hat = self.model(
                    batch_noisy,
                    num_iterations=self.config.num_iterations
                )

                mse = F.mse_loss(S_hat, batch_clean, reduction='sum')
                total_mse += mse.item()

                all_preds.append(S_hat.cpu().numpy())
                all_targets.append(batch_clean.cpu().numpy())

        predictions = np.concatenate(all_preds, axis=0)
        targets = np.concatenate(all_targets, axis=0)
        avg_mse = total_mse / len(predictions)

        return avg_mse, predictions, targets

    def predict_single(
        self,
        Y: np.ndarray,
        num_iterations: Optional[int] = None
    ) -> np.ndarray:
        """
        Predict for a single signal
        """
        if num_iterations is None:
            num_iterations = self.config.num_iterations

        self.model.eval()

        Y_tensor = torch.from_numpy(Y).unsqueeze(0).to(self.device)

        with torch.no_grad():
            S_hat = self.model(Y_tensor, num_iterations=num_iterations)

        return S_hat.cpu().numpy().squeeze(0)


# =============================================================================
# 8. VISUALIZATION AND ANALYSIS
# =============================================================================

class Visualizer:
    """Visualization of results"""

    @staticmethod
    def plot_training_history(history: List[float], save_path: Optional[str] = None):
        """Training history plot"""
        plt.figure(figsize=(10, 6))
        plt.plot(history, 'b-', linewidth=2)
        plt.xlabel('Epoch')
        plt.ylabel('MSE Loss')
        plt.title('Training History')
        plt.grid(True, alpha=0.3)
        plt.yscale('log')

        # if save_path:
        #     plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.show()

    @staticmethod
    def plot_signal_comparison(
        t: np.ndarray,
        clean: np.ndarray,
        noisy: np.ndarray,
        predicted: np.ndarray,
        save_path: Optional[str] = None
    ):
        """Signal comparison"""
        fig, axes = plt.subplots(3, 1, figsize=(12, 10))

        # Clean signal
        axes[0].plot(t, clean, 'g-', linewidth=2, label='Clean Signal')
        axes[0].set_title('Original Clean Signal')
        axes[0].legend()
        axes[0].grid(True, alpha=0.3)

        # Noisy signal
        axes[1].plot(t, noisy, 'r-', alpha=0.7, label='Noisy Signal')
        axes[1].set_title(f'Noisy Signal (SNR: {Visualizer._compute_snr(clean, noisy):.2f} dB)')
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)

        # Reconstructed signal
        axes[2].plot(t, clean, 'g--', linewidth=2, alpha=0.7, label='Clean (target)')
        axes[2].plot(t, predicted, 'b-', linewidth=2, label='Predicted')
        axes[2].set_title(f'Reconstructed Signal (MSE: {np.mean((clean-predicted)**2):.6f})')
        axes[2].legend()
        axes[2].grid(True, alpha=0.3)

        plt.tight_layout()

        # if save_path:
        #     plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.show()

    @staticmethod
    def plot_multiple_predictions(
        t: np.ndarray,
        predictions: np.ndarray,
        true_signal: np.ndarray,
        n_plot: int = 10
    ):
        """Show multiple predictions"""
        plt.figure(figsize=(12, 6))

        # First n_plot predictions
        for i in range(min(n_plot, len(predictions))):
            plt.plot(t, predictions[i], 'b-', alpha=0.3, linewidth=1)

        # Mean prediction
        mean_pred = predictions.mean(axis=0)
        plt.plot(t, mean_pred, 'k-', linewidth=3, label='Mean Prediction')

        # True signal
        plt.plot(t, true_signal, 'r--', linewidth=2, label='True Signal')

        plt.xlabel('Time')
        plt.ylabel('Amplitude')
        plt.title(f'Signal Predictions (n={len(predictions)})')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.show()

    @staticmethod
    def _compute_snr(clean: np.ndarray, noisy: np.ndarray) -> float:
        """Compute Signal-to-Noise Ratio (dB)"""
        signal_power = np.mean(clean**2)
        noise_power = np.mean((noisy - clean)**2)
        return 10 * np.log10(signal_power / noise_power)


# =============================================================================
# 9. MAIN EXECUTION FUNCTION
# =============================================================================

def main():
    """Main execution workflow"""

    # --- 1. Configuration ---
    config = ModelConfig(
        M=2048,
        epsilon=0.03,
        num_iterations=2,
        epochs=10,
        batch_size=64
    )
    noise=0.1
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}")
    print(f"Configuration: {config}")

    # --- 2. Data generation ---
    print("\n--- Data Generation ---")
    generator = SignalDatasetGenerator(config)

    # Training data
    Y_train, S_train = generator.generate_noisy_signals(n_samples=15, noise_eps=noise)
    print(f"Training data: {Y_train.shape}")

    # Test data (single signal type)
    Y_test, S_test, signal_name = generator.generate_single_type(
        n_samples=20, signal_type=2, noise_eps=noise  # Sawtooth
    )
    print(f"Test data ({signal_name}): {Y_test.shape}")

    # Create DataLoader
    train_dataset = SignalDataset(Y_train, S_train)
    train_loader = DataLoader(
        train_dataset,
        batch_size=config.batch_size,
        shuffle=True
    )

    # --- 3. Model creation ---
    print("\n--- Model Creation ---")
    param_grid = create_adaptive_param_grid(config.epsilon)

    model = RecurrentSLE(
        M=config.M,
        param_grid=param_grid,
        epsilon=config.epsilon,
        T=config.T,
        gating_hidden=config.gating_hidden
    ).to(device)

    print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

    # --- 4. Training ---
    print("\n--- Training Process ---")
    trainer = Trainer(model, config, device)
    history = trainer.train(train_loader)

    # --- 5. Visualization ---
    print("\n--- Results ---")
    Visualizer.plot_training_history(history)

    # Test on a single signal
    t = np.linspace(0, config.T, config.M)
    pred = trainer.predict_single(Y_test[0])

    Visualizer.plot_signal_comparison(
        t=t,
        clean=S_test[0],
        noisy=Y_test[0],
        predicted=pred
    )

    # Multiple predictions
    all_preds = [trainer.predict_single(Y_test[i]) for i in range(len(Y_test))]
    all_preds = np.array(all_preds)

    Visualizer.plot_multiple_predictions(t, all_preds, S_test[0])

    # MSE calculation
    mse = np.mean((all_preds - S_test)**2)
    print(f"\nAverage MSE: {mse:.6f}")

    print("\n--- Done ---")
    return model, trainer, history


# =============================================================================
# 10. ADDITIONAL FUNCTIONS (FOR ANALYSIS)
# =============================================================================

def analyze_optimal_parameters(
    model: RecurrentSLE,
    generator: SignalDatasetGenerator,
    config: ModelConfig,
    device: torch.device
):
    """
    Analyze optimal parameters for each signal type
    """
    print("\n=== Optimal Parameters Analysis ===")

    param_stats = []

    for signal_type in range(8):
        # Test data
        Y_test, S_test, name = generator.generate_single_type(
            n_samples=100, signal_type=signal_type, noise_eps=0.01
        )

        Y_tensor = torch.from_numpy(Y_test).to(device)

        model.eval()
        with torch.no_grad():
            _, weights = model(Y_tensor, return_all=True)

        # Find parameter with highest weight for each sample
        optimal_indices = torch.argmax(weights, dim=1).cpu().numpy()

        alphas, kappas, rs = [], [], []
        for idx in optimal_indices:
            a, k, r = model.candidate_params[idx]
            alphas.append(a)
            kappas.append(k)
            rs.append(r)

        param_stats.append({
            'name': name,
            'alpha_mean': np.mean(alphas),
            'alpha_std': np.std(alphas),
            'kappa_mean': np.mean(kappas),
            'kappa_std': np.std(kappas),
            'r_mean': np.mean(rs),
            'r_std': np.std(rs)
        })

        print(f"\n{name}:")
        print(f"  α = {np.mean(alphas):.4f} ± {np.std(alphas):.4f}")
        print(f"  κ = {np.mean(kappas):.4f} ± {np.std(kappas):.4f}")
        print(f"  r = {np.mean(rs):.4f} ± {np.std(rs):.4f}")

    return param_stats


# =============================================================================

if __name__ == "__main__":
    # Main execution
    model, trainer, history = main()

    # Optional additional analysis
    # config = ModelConfig()
    # generator = SignalDatasetGenerator(config)
    # device = next(model.parameters()).device
    # analyze_optimal_parameters(model, generator, config, device)

# -*- coding: utf-8 -*-
"""
SLE-RNN Model Analysis
======================

This script analyzes a trained RecurrentSLE model and:
1. Identifies optimal parameters for each signal type
2. Visualizes the MoE gating mechanism
3. Shows expert participation levels
4. Identifies "unused" experts

Usage:
    python analyze_model.py --model_path model.pth --output_dir analysis/
"""

import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Dict, List, Tuple, Optional
import json
from dataclasses import asdict
import warnings
warnings.filterwarnings('ignore')

# Import the main model code (or keep this file with the model file)
# If it's a separate file, adjust the import below:
# from your_model_file import RecurrentSLE, SignalDatasetGenerator, ModelConfig, create_adaptive_param_grid


class ModelAnalyzer:
    """
    Class for analyzing a trained SLE-RNN model
    """

    def __init__(self, model, config, device='cpu'):
        self.model = model
        self.config = config
        self.device = device
        self.model.eval()

        # Parameter list
        self.candidate_params = model.candidate_params
        self.L = len(self.candidate_params)

        # Statistics
        self.stats = {}

    def analyze_signal_type(
        self,
        Y_test: np.ndarray,
        S_test: np.ndarray,
        signal_name: str,
        n_samples: Optional[int] = None
    ) -> Dict:
        """
        Detailed analysis for a single signal type

        Returns:
            {
                'signal_name': str,
                'optimal_params': {
                    'alpha': (mean, std, best_value),
                    'kappa': (mean, std, best_value),
                    'r': (mean, std, best_value)
                },
                'expert_usage': array[L] - usage frequency of each expert,
                'gating_entropy': float - entropy of weights (randomness level),
                'dominant_experts': list - top 5 most active experts,
                'unused_experts': list - unused experts
            }
        """
        if n_samples is None:
            n_samples = len(Y_test)
        else:
            n_samples = min(n_samples, len(Y_test))

        Y_tensor = torch.from_numpy(Y_test[:n_samples]).to(self.device)

        with torch.no_grad():
            # Forward pass with return_all=True to get weights
            S_hat, weights = self.model(Y_tensor, return_all=True)

            # weights shape: (n_samples, L)
            weights_np = weights.cpu().numpy()

            # Expert with highest weight for each sample
            dominant_per_sample = np.argmax(weights_np, axis=1)

            # Usage frequency of each expert
            expert_usage = np.bincount(dominant_per_sample, minlength=self.L)
            expert_usage_freq = expert_usage / n_samples  # Normalization

            # Mean weights
            mean_weights = weights_np.mean(axis=0)

            # Most active experts (top 5)
            top5_indices = np.argsort(mean_weights)[-5:][::-1]
            dominant_experts = [
                {
                    'rank': i+1,
                    'expert_id': int(idx),
                    'alpha': self.candidate_params[idx][0],
                    'kappa': self.candidate_params[idx][1],
                    'r': self.candidate_params[idx][2],
                    'mean_weight': float(mean_weights[idx]),
                    'usage_frequency': float(expert_usage_freq[idx])
                }
                for i, idx in enumerate(top5_indices)
            ]

            # Unused experts (weight < 0.01)
            unused_threshold = 0.01 / self.L  # Below random expectation
            unused_mask = mean_weights < unused_threshold
            unused_experts = [
                {
                    'expert_id': int(i),
                    'alpha': params[0],
                    'kappa': params[1],
                    'r': params[2],
                    'mean_weight': float(mean_weights[i])
                }
                for i, params in enumerate(self.candidate_params)
                if unused_mask[i]
            ]

            # Gating entropy (how random vs how decisive)
            # High entropy = random, Low entropy = decisive
            eps = 1e-10
            entropy_per_sample = -np.sum(weights_np * np.log(weights_np + eps), axis=1)
            mean_entropy = float(entropy_per_sample.mean())
            max_possible_entropy = np.log(self.L)  # Maximum entropy
            normalized_entropy = mean_entropy / max_possible_entropy  # 0-1 range

            # Optimal parameter statistics (from dominant experts)
            optimal_alphas = [self.candidate_params[i][0] for i in dominant_per_sample]
            optimal_kappas = [self.candidate_params[i][1] for i in dominant_per_sample]
            optimal_rs = [self.candidate_params[i][2] for i in dominant_per_sample]

            result = {
                'signal_name': signal_name,
                'n_samples': n_samples,
                'optimal_params': {
                    'alpha': {
                        'mean': float(np.mean(optimal_alphas)),
                        'std': float(np.std(optimal_alphas)),
                        'median': float(np.median(optimal_alphas)),
                        'min': float(np.min(optimal_alphas)),
                        'max': float(np.max(optimal_alphas)),
                        'best': float(self.candidate_params[top5_indices[0]][0])
                    },
                    'kappa': {
                        'mean': float(np.mean(optimal_kappas)),
                        'std': float(np.std(optimal_kappas)),
                        'median': float(np.median(optimal_kappas)),
                        'min': float(np.min(optimal_kappas)),
                        'max': float(np.max(optimal_kappas)),
                        'best': float(self.candidate_params[top5_indices[0]][1])
                    },
                    'r': {
                        'mean': float(np.mean(optimal_rs)),
                        'std': float(np.std(optimal_rs)),
                        'median': float(np.median(optimal_rs)),
                        'min': float(np.min(optimal_rs)),
                        'max': float(np.max(optimal_rs)),
                        'best': float(self.candidate_params[top5_indices[0]][2])
                    }
                },
                'expert_usage': {
                    'frequencies': expert_usage_freq.tolist(),
                    'dominant_per_sample': dominant_per_sample.tolist()
                },
                'gating_entropy': {
                    'raw': mean_entropy,
                    'normalized': normalized_entropy,
                    'interpretation': 'Random' if normalized_entropy > 0.8 else
                                    'Partially determined' if normalized_entropy > 0.5 else
                                    'Clearly selected'
                },
                'dominant_experts': dominant_experts,
                'unused_experts': unused_experts,
                'performance': {
                    'mse': float(F.mse_loss(S_hat, torch.from_numpy(S_test[:n_samples]).to(self.device)).item())
                }
            }

            return result

    def analyze_all_signal_types(
        self,
        generator,
        noise_eps: float = 0.1,
        n_samples_per_type: int = 100
    ) -> Dict[str, Dict]:
        """
        Analyze all 8 signal types
        """
        all_results = {}

        signal_names = [
            "Sinusoidal", "Square wave", "Sawtooth", "Triangular",
            "Damped oscillation", "Gaussian Pulse", "Chirp", "Single pulse"
        ]

        print("=" * 80)
        print("ANALYSIS BY SIGNAL TYPE")
        print("=" * 80)

        for signal_type in range(8):
            print(f"\n--- {signal_names[signal_type]} ({signal_type}) ---")

            # Data generation
            Y_test, S_test, name = generator.generate_single_type(
                n_samples=n_samples_per_type,
                signal_type=signal_type,
                noise_eps=noise_eps
            )

            # Analysis
            result = self.analyze_signal_type(Y_test, S_test, name, n_samples_per_type)
            all_results[name] = result

            # Print to console
            self._print_single_analysis(result)

        self.stats = all_results
        return all_results

    def _print_single_analysis(self, result: Dict):
        """Pretty print a single analysis result"""
        p = result['optimal_params']

        print(f"  Optimal α: {p['alpha']['mean']:.4f} ± {p['alpha']['std']:.4f} "
              f"[best: {p['alpha']['best']:.4f}]")
        print(f"  Optimal κ: {p['kappa']['mean']:.4f} ± {p['kappa']['std']:.4f} "
              f"[best: {p['kappa']['best']:.4f}]")
        print(f"  Optimal r: {p['r']['mean']:.4f} ± {p['r']['std']:.4f} "
              f"[best: {p['r']['best']:.4f}]")
        print(f"  Gating entropy: {result['gating_entropy']['normalized']:.3f} "
              f"({result['gating_entropy']['interpretation']})")
        print(f"  MSE: {result['performance']['mse']:.6f}")

        print(f"\n  TOP 5 EXPERTS:")
        for expert in result['dominant_experts']:
            print(f"    #{expert['rank']}. Expert {expert['expert_id']}: "
                  f"α={expert['alpha']:.4f}, κ={expert['kappa']:.4f}, r={expert['r']:.4f} "
                  f"(w={expert['mean_weight']:.4f}, f={expert['usage_frequency']:.2%})")

        if result['unused_experts']:
            print(f"\n  UNUSED EXPERTS ({len(result['unused_experts'])}):")
            for exp in result['unused_experts'][:5]:  # Only first 5
                print(f"    Expert {exp['expert_id']}: w={exp['mean_weight']:.6f}")
            if len(result['unused_experts']) > 5:
                print(f"    ... and {len(result['unused_experts']) - 5} more")
        else:
            print(f"\n  All experts are used!")

    def visualize_moe_analysis(self, save_prefix: str = "moe_analysis"):
        """
        Visualizations for MoE analysis
        """
        if not self.stats:
            print("Please run analyze_all_signal_types() first!")
            return

        # 1. Expert usage for each signal type (heatmap)
        self._plot_expert_usage_heatmap(save_prefix)

        # 2. Dominant expert parameters (scatter plot)
        self._plot_dominant_experts_scatter(save_prefix)

        # 3. Gating entropy comparison
        self._plot_entropy_comparison(save_prefix)

        # 4. Unused experts
        self._plot_unused_experts(save_prefix)

        # 5. Global expert usage
        self._plot_global_expert_usage(save_prefix)

    def _plot_expert_usage_heatmap(self, save_prefix: str):
        """Expert usage heatmap"""
        signal_names = list(self.stats.keys())

        # Expert frequencies for each signal
        usage_matrix = np.array([
            self.stats[name]['expert_usage']['frequencies']
            for name in signal_names
        ])  # shape: (8, L)

        # Show only top 20 most active experts (for readability)
        mean_usage = usage_matrix.mean(axis=0)
        top20_indices = np.argsort(mean_usage)[-20:]

        usage_matrix_top20 = usage_matrix[:, top20_indices]

        plt.figure(figsize=(14, 8))
        sns.heatmap(
            usage_matrix_top20,
            xticklabels=[f"E{idx}" for idx in top20_indices],
            yticklabels=signal_names,
            cmap='YlOrRd',
            annot=False,
            cbar_kws={'label': 'Usage frequency'}
        )
        plt.title('MoE Expert Usage (Top 20)', fontsize=14)
        plt.xlabel('Expert ID', fontsize=12)
        plt.ylabel('Signal Type', fontsize=12)
        plt.tight_layout()
        # plt.savefig(f"{save_prefix}_expert_usage_heatmap.png", dpi=300, bbox_inches='tight')
        plt.show()
        # print(f"Saved: {save_prefix}_expert_usage_heatmap.png")

    def _plot_dominant_experts_scatter(self, save_prefix: str):
        """3D scatter of dominant expert parameters alpha-kappa-r"""
        fig, axes = plt.subplots(2, 4, figsize=(20, 10))
        axes = axes.flatten()

        colors = plt.cm.tab10(np.linspace(0, 1, 8))

        for idx, (name, result) in enumerate(self.stats.items()):
            ax = axes[idx]

            # Dominant expert parameters
            experts = result['dominant_experts']
            alphas = [e['alpha'] for e in experts]
            kappas = [e['kappa'] for e in experts]
            weights = [e['mean_weight'] for e in experts]

            # Bubble chart: x=alpha, y=kappa, size=weight
            scatter = ax.scatter(
                alphas, kappas,
                s=[w * 5000 for w in weights],  # Size proportional to weight
                c=[weights],
                cmap='viridis',
                alpha=0.6,
                edgecolors='black'
            )

            ax.set_xlabel('α (alpha)', fontsize=10)
            ax.set_ylabel('κ (kappa)', fontsize=10)
            ax.set_title(f'{name}\n(r={experts[0]["r"]:.2f})', fontsize=11)
            ax.grid(True, alpha=0.3)

            # Colorbar
            plt.colorbar(scatter, ax=ax, label='Weight')

        # plt.suptitle('Dominant Expert Parameters (Bubble size = Weight)', fontsize=16)
        plt.tight_layout()
        # plt.savefig(f"{save_prefix}_dominant_experts_scatter.png", dpi=300, bbox_inches='tight')
        plt.show()
        # print(f"Saved: {save_prefix}_dominant_experts_scatter.png")

    def _plot_entropy_comparison(self, save_prefix: str):
        """Gating entropy comparison"""
        signal_names = list(self.stats.keys())
        entropies = [self.stats[name]['gating_entropy']['normalized'] for name in signal_names]

        fig, ax = plt.subplots(figsize=(12, 6))

        bars = ax.barh(signal_names, entropies, color=plt.cm.RdYlGn_r(np.array(entropies)))

        # Write values
        for i, (name, val) in enumerate(zip(signal_names, entropies)):
            ax.text(val + 0.02, i, f'{val:.3f}', va='center', fontsize=10)

        ax.set_xlim(0, 1)
        ax.set_xlabel('Normalized Entropy', fontsize=12)
        ax.set_title('MoE Gate Entropy (0=Definite choice, 1=Random)', fontsize=14)
        ax.axvline(x=0.5, color='red', linestyle='--', alpha=0.5, label='Random border')
        ax.legend()

        plt.tight_layout()
        # plt.savefig(f"{save_prefix}_entropy_comparison.png", dpi=300, bbox_inches='tight')
        plt.show()
        # print(f"Saved: {save_prefix}_entropy_comparison.png")

    def _plot_unused_experts(self, save_prefix: str):
        """Show unused experts"""
        all_unused = set()
        unused_by_signal = {}

        for name, result in self.stats.items():
            unused_ids = [e['expert_id'] for e in result['unused_experts']]
            unused_by_signal[name] = unused_ids
            all_unused.update(unused_ids)

        if not all_unused:
            print("No unused experts!")
            return

        # Which experts are unused for which signals
        matrix = np.zeros((len(self.stats), len(all_unused)))
        signal_list = list(self.stats.keys())
        unused_list = sorted(list(all_unused))

        for i, name in enumerate(signal_list):
            for j, exp_id in enumerate(unused_list):
                if exp_id in unused_by_signal[name]:
                    matrix[i, j] = 1

        plt.figure(figsize=(max(10, len(unused_list) * 0.5), 8))
        sns.heatmap(
            matrix,
            xticklabels=[f"E{eid}" for eid in unused_list],
            yticklabels=signal_list,
            cmap='Reds',
            cbar_kws={'label': 'Not used (1) / Used (0)'},
            linewidths=0.5
        )
        plt.title(f'Unused Experts ({len(all_unused)})', fontsize=14)
        plt.xlabel('Expert ID', fontsize=12)
        plt.ylabel('Signal Type', fontsize=12)
        plt.tight_layout()
        # plt.savefig(f"{save_prefix}_unused_experts.png", dpi=300, bbox_inches='tight')
        plt.show()
        # print(f"Saved: {save_prefix}_unused_experts.png")

        # Statistics
        print(f"\nUnused experts statistics:")
        print(f"  Total unused: {len(all_unused)} / {self.L} ({len(all_unused)/self.L:.1%})")
        for name, unused in unused_by_signal.items():
            if unused:
                print(f"  {name}: {len(unused)} experts unused")

    def _plot_global_expert_usage(self, save_prefix: str):
        """Global expert usage (average across all signals)"""
        global_usage = np.zeros(self.L)

        for result in self.stats.values():
            global_usage += np.array(result['expert_usage']['frequencies'])

        global_usage /= len(self.stats)  # Average

        # Sort
        sorted_indices = np.argsort(global_usage)[::-1]

        plt.figure(figsize=(14, 6))

        # Bar plot
        plt.bar(
            range(self.L),
            global_usage[sorted_indices],
            color=plt.cm.viridis(np.linspace(0, 1, self.L))
        )

        # Mark top 10
        for i in range(min(10, self.L)):
            idx = sorted_indices[i]
            plt.text(
                i, global_usage[idx] + 0.001,
                f'E{idx}\nα={self.candidate_params[idx][0]:.2f}\nκ={self.candidate_params[idx][1]:.2f}',
                ha='center', va='bottom', fontsize=7, rotation=0
            )

        plt.xlabel('Expert (sorted)', fontsize=12)
        plt.ylabel('Average usage frequency', fontsize=12)
        plt.title('Global Expert Usage (Across All Signals)', fontsize=14)
        plt.tight_layout()
        # plt.savefig(f"{save_prefix}_global_expert_usage.png", dpi=300, bbox_inches='tight')
        plt.show()
        # print(f"Saved: {save_prefix}_global_expert_usage.png")

    def generate_report(self, filename: str = "analysis_report.json"):
        """Save analysis results in JSON format"""
        if not self.stats:
            print("Please run analysis first!")
            return

        # Convert numpy arrays to lists
        report = {}
        for name, result in self.stats.items():
            report[name] = result

        with open(filename, 'w') as f:
            json.dump(report, f, indent=2)

        print(f"\nAnalysis report saved: {filename}")

    def print_summary_table(self):
        """Print summary table"""
        if not self.stats:
            return

        print("\n" + "=" * 100)
        print("SUMMARY TABLE")
        print("=" * 100)
        print(f"{'Signal':<20} {'α (best)':<10} {'κ (best)':<10} {'r (best)':<10} "
              f"{'Entropy':<12} {'MSE':<10} {'Unused':<10}")
        print("-" * 100)

        for name, result in self.stats.items():
            p = result['optimal_params']
            n_unused = len(result['unused_experts'])
            print(f"{name:<20} "
                  f"{p['alpha']['best']:<10.4f} "
                  f"{p['kappa']['best']:<10.4f} "
                  f"{p['r']['best']:<10.4f} "
                  f"{result['gating_entropy']['normalized']:<12.3f} "
                  f"{result['performance']['mse']:<10.6f} "
                  f"{n_unused:<10}")


# =============================================================================
# MAIN EXECUTION FUNCTION
# =============================================================================

def run_analysis(model, config, generator, device='cpu', output_dir='./analysis'):
    """
    Run full analysis

    Args:
        model: Trained RecurrentSLE model
        config: ModelConfig
        generator: SignalDatasetGenerator
        device: 'cpu' or 'cuda'
        output_dir: Directory to save results
    """
    import os
    os.makedirs(output_dir, exist_ok=True)

    # Create analyzer
    analyzer = ModelAnalyzer(model, config, device)

    # 1. Analyze all signal types
    print("\n" + "=" * 80)
    print("1. SIGNAL ANALYSIS")
    print("=" * 80)
    stats = analyzer.analyze_all_signal_types(generator, noise_eps=0.1, n_samples_per_type=100)

    # 2. Summary table
    analyzer.print_summary_table()

    # 3. Visualizations
    print("\n" + "=" * 80)
    print("2. VISUALIZATIONS")
    print("=" * 80)
    # analyzer.visualize_moe_analysis(save_prefix=f"{output_dir}/moe")

    # 4. Save report
    # analyzer.generate_report(f"{output_dir}/analysis_report.json")

    print("\n" + "=" * 80)
    print("3. KEY FINDINGS")
    print("=" * 80)

    # Most used experts
    print("\nMost frequently used experts:")
    global_usage = np.zeros(analyzer.L)
    for result in stats.values():
        global_usage += np.array(result['expert_usage']['frequencies'])
    global_usage /= len(stats)

    top5_global = np.argsort(global_usage)[-5:][::-1]
    for rank, idx in enumerate(top5_global, 1):
        alpha, kappa, r = analyzer.candidate_params[idx]
        print(f"  #{rank}. Expert {idx}: α={alpha:.4f}, κ={kappa:.4f}, r={r:.4f} "
              f"(f={global_usage[idx]:.2%})")

    # Total unused
    all_unused = set()
    for result in stats.values():
        all_unused.update([e['expert_id'] for e in result['unused_experts']])

    print(f"\nTotal unused experts: {len(all_unused)} / {analyzer.L} "
          f"({len(all_unused)/analyzer.L:.1%})")

    return analyzer


# =============================================================================
# EXAMPLE USAGE (main)
# =============================================================================

if __name__ == "__main__":
    """
    EXAMPLE: If the model is already trained, use as follows:

    # Load model
    model = RecurrentSLE(...)
    model.load_state_dict(torch.load('model.pth'))

    # Create generator
    config = ModelConfig(M=100, epsilon=0.01)
    generator = SignalDatasetGenerator(config)

    # Analysis
    analyzer = run_analysis(model, config, generator, device='cpu')
    """
    # EXAMPLE: If the model is already trained, use as follows:

    # Load model
    model = model
    # model.load_state_dict(torch.load('model.pth'))

    # Create generator
    config = ModelConfig(M=2048, epsilon=0.05)
    generator = SignalDatasetGenerator(config)

    # Analysis
    analyzer = run_analysis(model, config, generator, device='cpu')


    print("""
    ============================================================
    MODEL ANALYSIS SCRIPT
    ============================================================

    This script analyzes a trained RecurrentSLE model.

    Usage:
        1. Load your model
        2. Create ModelAnalyzer class
        3. Run analyze_all_signal_types()
        4. Call visualize_moe_analysis()

    Example code:
        model = RecurrentSLE(...)  # Your model
        model.load_state_dict(torch.load('model.pth'))

        analyzer = ModelAnalyzer(model, config, device)
        analyzer.analyze_all_signal_types(generator)
        analyzer.visualize_moe_analysis()
        analyzer.print_summary_table()
    """)

import torch
import os

# File name for saving the model
model_save_path = 'recurrent_sle_model_005.pth'

# Save the model's state_dict (trained parameters)
# This is the most recommended approach as it allows storing the model architecture in code
torch.save(model.state_dict(), model_save_path)

print(f"Model successfully saved: {model_save_path}")

# =============================================================================
# How to load and use the saved model in a different environment
# =============================================================================

print("\n--- Instructions for loading and using the saved model in another environment ---")
print("To load and use the model in another environment, the following steps are required:")
print("1. Ensure all model classes (ModelConfig, ParameterGrid, SpectralReconstructor, RecurrentSLE, and SignalDatasetGenerator) are defined.")
print("   To do this, run the main code block named 'AdtHgfGm6fBu' in your new environment.")
print("2. The saved model file ('recurrent_sle_model.pth') must be available in the new environment.")

# Example code: Loading process (not used in this block, just for guidance)
print("\nThe following code snippet shows how to load and use the saved model:")

loading_example_code = """
# 1. Import required libraries
import torch
import numpy as np

# 2. Define model configuration and helper classes
#    (Requires running the main model code (AdtHgfGm6fBu) in the new environment)
#    model = RecurrentSLE(...) requires config and param_grid.

# Recreate the configuration used in training
loaded_config = ModelConfig(
    M=2048,
    epsilon=0.05,
    num_iterations=2,
    epochs=10,
    batch_size=64
)
loaded_param_grid = create_adaptive_param_grid(loaded_config.epsilon)

# Create a new instance of the model (without parameters)
loaded_model = RecurrentSLE(
    M=loaded_config.M,
    param_grid=loaded_param_grid,
    epsilon=loaded_config.epsilon,
    T=loaded_config.T,
    gating_hidden=loaded_config.gating_hidden
)

# Move the model to the target device (CPU or GPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
loaded_model.to(device)

# 3. Load the saved state_dict
model_save_path = 'recurrent_sle_model.pth' # File path
loaded_model.load_state_dict(torch.load(model_save_path, map_location=device))

# 4. Set the model to evaluation mode
loaded_model.eval()

print(f"Model '{model_save_path}' successfully loaded.")

# 5. Example usage of the loaded model:
# Create a new noisy signal (example)
loaded_generator = SignalDatasetGenerator(loaded_config)
Y_new, S_clean_new, _ = loaded_generator.generate_single_type(
    n_samples=1, signal_type=0, noise_eps=0.1 # Sinusoidal signal, 0.1 noise
)

# Prepare the signal for the model
noisy_signal_to_denoise = Y_new[0].astype(np.float32)

# Denoise the signal
with torch.no_grad():
    denoised_signal_tensor = loaded_model(torch.from_numpy(noisy_signal_to_denoise).unsqueeze(0).to(device))
    denoised_signal_numpy = denoised_signal_tensor.cpu().numpy().squeeze(0)

print("New signal successfully denoised.")
"""

print(f"""```python\n{loading_example_code}\n```""")

print("Using the instructions and code snippet above, you can reuse the trained model in any environment.")

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# ------------------------------
# 1. Create HeaviSine signal
# ------------------------------
def heavisine(t):
    """
    HeaviSine signal - test signal proposed by Donoho (1994)
    f(t) = 4 * sin(4 * pi * t) - sgn(t - 0.3) - sgn(0.72 - t)
    """
    # 4*sin(4*pi*t) part
    sin_part = 4 * np.sin(4 * np.pi * t)

    # sgn(t - 0.3) part: -1 if t < 0.3, 1 if t >= 0.3
    sgn1 = np.where(t < 0.3, -1, 1)

    # sgn(0.72 - t) part: 1 if t < 0.72, -1 if t >= 0.72
    sgn2 = np.where(t < 0.72, 1, -1)

    return sin_part - sgn1 - sgn2


# ------------------------------
# 2. Set parameters
# ------------------------------
np.random.seed(42)  # For reproducible results

# Time discretization
n = 2048  # signal length (large enough as in the paper)
t = np.linspace(0, 1, n, endpoint=False)

# Original noise-free signal
signall = heavisine(t)
scale = np.max(np.abs(signall))
signal_clean = signall/scale

# Noise parameters
sigma = 0.2  # standard deviation (as in the paper)

print(scale)
noise = np.random.normal(loc=0, scale=sigma, size=n)/scale

# Noisy signal (additive noise)
signal_noisy = (signal_clean + noise)

# ------------------------------
# 3. Statistics
# ------------------------------
print("=" * 50)
print("NOISE STATISTICS")
print("=" * 50)
print(f"Noise mean: {np.mean(noise):.6f}")
print(f"Noise std:  {np.std(noise):.6f}")
print(f"Expected sigma:                  {sigma}")
print(f"Noise variance:      {np.var(noise):.6f}")
print(f"Expected sigma^2:                {sigma**2}")

# Calculate SNR (Signal-to-Noise Ratio)
signal_power = np.mean(signal_clean ** 2)
noise_power = np.mean(noise ** 2)
snr = 10 * np.log10(signal_power / noise_power)
print(f"\nSignal-to-Noise Ratio (SNR): {snr:.2f} dB")

# ------------------------------
# 4. Visualization (similar to Figure 2 in the paper)
# ------------------------------
fig, axes = plt.subplots(2, 1, figsize=(14, 8))

# Top panel: Noise-free signal
axes[0].plot(t, signal_clean, 'b-', linewidth=1, label='Noise-free signal')
axes[0].set_xlim(0, 1)
axes[0].set_ylim(-6, 6)
axes[0].set_ylabel('Amplitude', fontsize=12)
axes[0].set_title('HeaviSine signal - noise-free', fontsize=14)
axes[0].grid(True, alpha=0.3)
axes[0].legend(loc='upper right')

# Bottom panel: Noisy signal
axes[1].plot(t, signal_noisy, 'r-', linewidth=0.8, alpha=0.7, label=f'Noisy signal ($\\sigma$ = {sigma})')
# Overlay the original signal for comparison
axes[1].plot(t, signal_clean, 'b-', linewidth=1, alpha=0.5, label='Original signal')
axes[1].set_xlim(0, 1)
axes[1].set_ylim(-6, 6)
axes[1].set_xlabel('Time (t)', fontsize=12)
axes[1].set_ylabel('Amplitude', fontsize=12)
axes[1].set_title('HeaviSine signal with added Gaussian noise', fontsize=14)
axes[1].grid(True, alpha=0.3)
axes[1].legend(loc='upper right')

plt.tight_layout()
plt.savefig('heavisine_signal.png', dpi=150, bbox_inches='tight')
plt.show()

# ------------------------------
# 5. Zoomed-in view (to see noise effect more clearly)
# ------------------------------
fig, ax = plt.subplots(figsize=(14, 5))

# Show the 0.2 to 0.4 time segment
mask = (t >= 0.2) & (t <= 0.4)
t_zoom = t[mask]
clean_zoom = signal_clean[mask]
noisy_zoom = signal_noisy[mask]

ax.plot(t_zoom, clean_zoom, 'b-', linewidth=2, label='Original signal (noise-free)')
ax.plot(t_zoom, noisy_zoom, 'r-', linewidth=1, alpha=0.8, label='Noisy signal')
ax.fill_between(t_zoom, clean_zoom, noisy_zoom, alpha=0.3, color='gray', label='Noise (difference)')
ax.set_xlabel('Time (t)', fontsize=12)
ax.set_ylabel('Amplitude', fontsize=12)
ax.set_title(f'HeaviSine signal - zoomed view (noise std = {sigma})', fontsize=14)
ax.legend(loc='upper right')
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('heavisine_zoom.png', dpi=150, bbox_inches='tight')
plt.show()

# ------------------------------
# 6. Verify noise distribution (Gaussian)
# ------------------------------
fig, ax = plt.subplots(1, 2, figsize=(12, 4))

# Histogram
ax[0].hist(noise, bins=50, density=True, alpha=0.7, color='gray', edgecolor='black')
# Gaussian curve
x = np.linspace(-0.8, 0.8, 100)
gaussian = stats.norm.pdf(x, 0, sigma)
ax[0].plot(x, gaussian, 'r-', linewidth=2, label=f'N(0, {sigma}²)')
ax[0].set_xlabel('Noise value', fontsize=12)
ax[0].set_ylabel('Density', fontsize=12)
ax[0].set_title('Noise distribution (histogram)', fontsize=12)
ax[0].legend()
ax[0].grid(True, alpha=0.3)

# Q-Q plot (normal probability plot)
stats.probplot(noise, dist="norm", plot=ax[1])
ax[1].set_title('Q-Q plot (normality test)', fontsize=12)
ax[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('noise_distribution.png', dpi=150, bbox_inches='tight')
plt.show()

# ------------------------------
# 7. Comparison for different sigma values
# ------------------------------
sigmas = [0.1, 0.2, 0.3, 0.5]
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
axes = axes.flatten()

for idx, s in enumerate(sigmas):
    noise_temp = np.random.normal(0, s, n)
    signal_temp = signal_clean + noise_temp

    axes[idx].plot(t, signal_clean, 'b-', linewidth=1, alpha=0.5, label='Original')
    axes[idx].plot(t, signal_temp, 'r-', linewidth=0.8, alpha=0.7, label=f'Noisy ($\\sigma$={s})')
    axes[idx].set_xlim(0, 1)
    axes[idx].set_ylim(-6, 6)
    axes[idx].set_title(f'HeaviSine - sigma = {s}')
    axes[idx].grid(True, alpha=0.3)
    axes[idx].legend(loc='upper right')

plt.tight_layout()
plt.savefig('heavisine_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n" + "=" * 50)
print("DONE: All plots saved")
print("=" * 50)

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr # For NCC calculation

# Note: If the trainer and model objects are not re-run,
# please re-run the cell that calls the 'main()' function.
# The model's internal 'M' configuration should be 2048.

# 1. Denoise the noisy signal using the model
print("Denoising the noisy signal using the model...")
# Convert signal_noisy to float32 - important!
denoised_signal = trainer.predict_single(signal_noisy.astype(np.float32))
print("Denoising completed.")

# 2. Calculate MSE (Mean Squared Error)
# Convert clean signal to float32 for comparison
mse = np.mean((signal_clean.astype(np.float32) - denoised_signal)**2)
print(f"\nMean Squared Error (MSE): {mse:.6f}")

# 3. Calculate SNR (Signal-to-Noise Ratio)
def calculate_snr(clean_signal, noisy_signal):
    signal_power = np.mean(clean_signal**2)
    noise_power = np.mean((noisy_signal - clean_signal)**2)
    if noise_power == 0:
        return float('inf')
    return 10 * np.log10(signal_power / noise_power)

# Convert to float32 for SNR calculation
snr_noisy = calculate_snr(signal_clean.astype(np.float32), signal_noisy.astype(np.float32))
snr_denoised = calculate_snr(signal_clean.astype(np.float32), denoised_signal)
print(f"SNR of noisy signal: {snr_noisy:.2f} dB")
print(f"SNR of denoised signal: {snr_denoised:.2f} dB")

# 4. Calculate NCC (Normalized Cross-Correlation)
def calculate_ncc(signal1, signal2):
    # Pearson correlation coefficient is a common form of NCC
    return pearsonr(signal1, signal2)[0]

ncc_noisy = calculate_ncc(signal_clean.astype(np.float32), signal_noisy.astype(np.float32))
ncc_denoised = calculate_ncc(signal_clean.astype(np.float32), denoised_signal)
print(f"NCC of noisy signal: {ncc_noisy:.4f}")
print(f"NCC of denoised signal: {ncc_denoised:.4f}")

# 5. Display results in a single plot
print("Displaying results in a plot...")

# Set matplotlib style and font sizes
plt.style.use('seaborn-v0_8-whitegrid') # Apply a good design style
plt.rcParams.update({
    'font.size': 24,
    'axes.titlesize': 24,
    'axes.labelsize': 20,
    'legend.fontsize': 24,
    'xtick.labelsize': 18,
    'ytick.labelsize': 18,
    'figure.titlesize': 20 # For the overall title
})

plt.figure(figsize=(15, 7))
plt.plot(t, signal_clean, 'g-', linewidth=2, label='Original signal')
plt.plot(t, signal_noisy, 'r-', alpha=0.7, label='Noisy signal')
plt.plot(t, denoised_signal, 'b-', linewidth=2, label='Predict')

# plt.title('Comparison of Original, Noisy, and Reconstructed Signal')
plt.xlabel('Time')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True, alpha=0.6)
plt.tight_layout()
plt.show()
print("Plot successfully displayed.")

import numpy as np

def compute_snr(original, denoised):
    """
    Computes Signal-to-Noise Ratio (SNR).
    Formula: SNR = 10 * log10( sum(x^2) / sum((y - x)^2) )

    Parameters:
    original : ndarray - original noise-free signal (x)
    denoised : ndarray - denoised signal (y)

    Returns:
    snr : float - SNR value in decibels
    """
    original = np.asarray(original)
    denoised = np.asarray(denoised)

    signal_power = np.sum(original ** 2)
    noise_power = np.sum((denoised - original) ** 2)

    # Avoid division by very small numbers
    if noise_power == 0:
        return np.inf

    snr = 10 * np.log10(signal_power / noise_power)
    return snr

def compute_mse(original, denoised):
    """
    Computes Mean Squared Error (MSE).
    Formula: MSE = (1/n) * sum((y - x)^2)

    Parameters:
    original : ndarray - original noise-free signal (x)
    denoised : ndarray - denoised signal (y)

    Returns:
    mse : float - mean squared error
    """
    original = np.asarray(original)
    denoised = np.asarray(denoised)

    mse = np.mean((denoised - original) ** 2)
    return mse

def compute_ncc(original, denoised):
    """
    Computes Normalized Cross-Correlation (NCC).
    Formula: NCC = sum(x * y) / sqrt( sum(x^2) * sum(y^2) )

    Parameters:
    original : ndarray - original noise-free signal (x)
    denoised : ndarray - denoised signal (y)

    Returns:
    ncc : float - correlation coefficient (0 to 1, 1 is best)
    """
    original = np.asarray(original)
    denoised = np.asarray(denoised)

    numerator = np.sum(original * denoised)
    denominator = np.sqrt(np.sum(original ** 2) * np.sum(denoised ** 2))

    if denominator == 0:
        return 0.0

    ncc = numerator / denominator
    return ncc

clean = signal_clean
noisy = signal_noisy
denoised = denoised_signal

snr_noisy = compute_snr(clean, noisy)
snr_denoised = compute_snr(clean, denoised)
mse_noisy = compute_mse(clean, noisy)
mse_denoised = compute_mse(clean, denoised)
ncc_noisy = compute_ncc(clean, noisy)
ncc_denoised = compute_ncc(clean, denoised)

print("=" * 50)
print("FOR NOISY SIGNAL:")
print(f"  SNR: {snr_noisy:.4f} dB")
print(f"  MSE: {mse_noisy:.6f}")
print(f"  NCC: {ncc_noisy:.6f}")
print("\nFOR DENOISED SIGNAL:")
print(f"  SNR: {snr_denoised:.4f} dB")
print(f"  MSE: {mse_denoised:.6f}")
print(f"  NCC: {ncc_denoised:.6f}")
print("=" * 50)

print("\n--- Comparison of predictions for different signals and noise levels ---")

def plot_multi_signal_noise_comparison(
    t: np.ndarray,
    results: List[Dict], # List of {'signal_type_name', 'noise_eps', 'clean', 'noisy', 'predicted'}
    title: str = 'Model Predictions Across Different Signals and Noise Levels',
    save_path: Optional[str] = None
):
    unique_signal_names = sorted(list(set([r['signal_type_name'] for r in results])))
    unique_noise_eps = sorted(list(set([r['noise_eps'] for r in results])))

    num_signals = len(unique_signal_names)
    num_noise_levels = len(unique_noise_eps)

    fig, axes = plt.subplots(
        num_signals, num_noise_levels,
        figsize=(num_noise_levels * 6, num_signals * 4),
        sharex=True, sharey=True
    )

    if num_signals == 1 and num_noise_levels == 1:
        axes = np.array([[axes]]) # Ensure axes is 2D for consistent indexing
    elif num_signals == 1:
        axes = np.expand_dims(axes, axis=0) # Ensure axes is 2D
    elif num_noise_levels == 1:
        axes = np.expand_dims(axes, axis=1) # Ensure axes is 2D

    for i, signal_name in enumerate(unique_signal_names):
        for j, noise_eps in enumerate(unique_noise_eps):
            ax = axes[i, j]
            current_result = next(
                (r for r in results if r['signal_type_name'] == signal_name and r['noise_eps'] == noise_eps),
                None
            )

            if current_result:
                clean = current_result['clean']
                noisy = current_result['noisy']
                predicted = current_result['predicted']

                ax.plot(t, clean, 'g--', label='Clean Signal', alpha=0.8, linewidth=2)
                ax.plot(t, noisy, 'r-', label='Noisy Signal', alpha=0.5)
                ax.plot(t, predicted, 'b-', label='Predicted Signal', alpha=0.8)

                if i == 0: # Title for columns (noise levels)
                    ax.set_title(f'Noise: {noise_eps}', fontsize=12)

                if j == 0: # Label for rows (signal types)
                    ax.text(-0.1, 0.5, signal_name, rotation=90, va='center', ha='right', transform=ax.transAxes, fontsize=12)

                if i == num_signals - 1: # X-label for bottom row
                    ax.set_xlabel('Time')

                # Calculate MSE for title
                mse = np.mean((clean - predicted)**2)
                ax.text(0.05, 0.9, f'MSE: {mse:.4f}', transform=ax.transAxes, fontsize=8, verticalalignment='top', bbox=dict(boxstyle='round,pad=0.2', fc='yellow', alpha=0.5))

                ax.grid(True, alpha=0.3)

    # Add a single legend outside all subplots
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='upper right', bbox_to_anchor=(0.99, 0.99), fontsize=10)

    plt.suptitle(title, y=1.02, fontsize=16)
    plt.tight_layout(rect=[0.05, 0.03, 0.95, 0.97]) # Adjust layout to make space for suptitle and legend

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.show()


# --- Parameters for comparison ---
# Select several signal types (indices from SignalGenerators.get_all_generators())
signal_types_to_compare = [
    0, # Sinusoidal
    1, # Square wave
    2,3,4,5,6,7  # Gaussian Pulse
]
signal_names_map = [
    "Sinusoidal", "Square wave", "Sawtooth", "Triangular",
    "Damped oscillation", "Gaussian Pulse", "Chirp", "Single pulse"
]

# Select several noise levels
noise_levels_to_compare = [0.5]

# Time for the signal
t = np.linspace(0, config.T, 300)

comparison_results = []

print(f"Starting data generation for {len(signal_types_to_compare)} signals and {len(noise_levels_to_compare)} noise levels...")

for signal_type_idx in signal_types_to_compare:
    current_signal_name = signal_names_map[signal_type_idx]
    for noise_eps in noise_levels_to_compare:
        print(f"  Generating: {current_signal_name}, Epsilon={noise_eps}")

        # Generate the test signal with the current noise level
        Y_test_single, S_test_single, _ = generator.generate_single_type(
            n_samples=1, # Only one sample
            signal_type=signal_type_idx,
            noise_eps=noise_eps
        )

        # Predict the reconstructed signal
        predicted_signal = trainer.predict_single(Y_test_single[0])

        comparison_results.append({
            'signal_type_name': current_signal_name,
            'noise_eps': noise_eps,
            'clean': S_test_single[0],
            'noisy': Y_test_single[0],
            'predicted': predicted_signal
        })

print("Data generated. Plotting...")

# Create the comprehensive plot
plot_multi_signal_noise_comparison(
    t=t,
    results=comparison_results,
    title='Model Prediction Comparison for Different Signals and Noise Levels',
    save_path='./analysis/multi_signal_noise_comparison.png'
)

print("Comparison plot created and saved to ./analysis/multi_signal_noise_comparison.png")

import pandas as pd
import numpy as np

# Define the epsilon values requested by the user
epsilon_values = [0.05, 0.1, 0.3, 0.5, 1.0]

# Prepare to store results
results_table = []

print("\n--- MSE analysis by epsilon for each signal type ---\n")

# Iterate through each of the 8 signal types
for signal_type_idx in range(8):
    current_signal_name = signal_names_map[signal_type_idx]
    row_data = {'Signal type': current_signal_name}

    print(f"Signal type: {current_signal_name}")

    # Generate the *clean* signal once for the current signal type
    # We generate it with noise_eps=0 to ensure we get the pure clean signal.
    # generator.generate_single_type returns (noisy, clean, name)
    # Since n_samples=1, S_test_base_single_sample_array will be an array of shape (1, M)
    _, S_test_base_single_sample_array, _ = generator.generate_single_type(
        n_samples=1,
        signal_type=signal_type_idx,
        noise_eps=0 # Generate a clean signal
    )
    S_clean_signal = S_test_base_single_sample_array[0] # Extract the single clean signal (shape M,)

    # Iterate through each epsilon value to add different noise levels to the SAME clean signal
    for eps in epsilon_values:
        # Create a *new noisy version* of the *same clean signal* for the current epsilon
        M = config.M # Get signal length from config
        # Ensure noise is generated as float32 to match model's expected dtype
        noise = eps * np.random.normal(0, 1, size=M).astype(np.float32)
        Y_noisy_for_current_eps = S_clean_signal + noise

        # Predict the reconstructed signal from this specific noisy version
        # trainer.predict_single will convert this numpy array to a torch.tensor
        # which will then have the correct dtype (float32)
        predicted_signal = trainer.predict_single(Y_noisy_for_current_eps)

        # Calculate Mean Squared Error (MSE) using the *original clean signal*
        mse = np.mean((predicted_signal - S_clean_signal)**2)
        row_data[f'Epsilon={eps}'] = f'{mse:.6f}'

    results_table.append(row_data)

# Create a pandas DataFrame for better table formatting
df_mse = pd.DataFrame(results_table)

print("\n--- MSE results table ---\n")
print(df_mse.to_markdown(index=False))

print("\nAnalysis completed.")

print("\n--- Signal comparison at different epsilon (noise) levels ---")

# Different epsilon values for display
noise_levels_for_display = [0.01, 0.05, 0.1, 0.3, 0.5, 1.0]

# Select a signal type for testing (e.g., 0 - Sinusoidal signal)
signal_type_to_test = 7
selected_signal_name = signal_names_map[signal_type_to_test]

# Time grid for the signal
t = np.linspace(0, config.T, config.M)

print(f"\nSelected signal type: {selected_signal_name}\n")

# Generate the clean signal once (noise-free)
_, S_clean_single_array, _ = generator.generate_single_type(
    n_samples=1,
    signal_type=signal_type_to_test,
    noise_eps=0 # To get the clean signal
)
S_clean_signal = S_clean_single_array[0]

# Set matplotlib style and font sizes
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams.update({
    'font.size': 18,
    'axes.titlesize': 20,
    'axes.labelsize': 16,
    'legend.fontsize': 16,
    'xtick.labelsize': 16,
    'ytick.labelsize': 16,
    'figure.titlesize': 22
})

for noise_eps in noise_levels_for_display:
    print(f"Testing with epsilon = {noise_eps}")

    # Add noise to the clean signal at the current epsilon level
    noise = noise_eps * np.random.normal(0, 1, size=config.M).astype(np.float32)
    Y_noisy_for_display = S_clean_signal + noise

    # Predict the reconstructed signal
    predicted_signal = trainer.predict_single(Y_noisy_for_display)

    # Visualize the results in a single plot
    plt.figure(figsize=(12, 6))
    plt.plot(t, Y_noisy_for_display, 'r-', alpha=0.7, label='Noisy Signal')
    plt.plot(t, S_clean_signal, 'g--', linewidth=2, label='Original Signal')
    plt.plot(t, predicted_signal, 'b-', linewidth=2, label='Predicted Signal')

    # plt.title(f'Signal Comparison (Epsilon = {noise_eps}, Type: {selected_signal_name})')
    plt.xlabel('Time')
    plt.ylabel('Amplitude')
    plt.legend()
    plt.grid(True, alpha=0.6) # Make grid lines more visible
    plt.tight_layout()
    plt.show()

print("\nVisualization completed.")

# Assuming config, trainer, generator, t, signal_names_map are available from previous cells.
# Ensure all necessary imports are present for this cell, though they should be from AdtHgfGm6fBu
import numpy as np
import matplotlib.pyplot as plt
import torch
import pandas as pd

# --- 1. Define new combined signal generation functions ---

def generate_sinus_square(t: np.ndarray) -> np.ndarray:
    return SignalGenerators.sinusoidal(t) + SignalGenerators.square_wave(t)

def generate_sinus_chirp(t: np.ndarray) -> np.ndarray:
    return SignalGenerators.sinusoidal(t) + SignalGenerators.chirp(t)

def generate_square_damp(t: np.ndarray) -> np.ndarray:
    return SignalGenerators.square_wave(t) + SignalGenerators.damped_oscillation(t)

def generate_sinus_half_square_half(t: np.ndarray, M: int) -> np.ndarray:
    mid_point = M // 2
    t_first_half = t[:mid_point]
    t_second_half = t[mid_point:]
    signal_first_half = SignalGenerators.sinusoidal(t_first_half)
    signal_second_half = SignalGenerators.square_wave(t_second_half)
    return np.concatenate((signal_first_half, signal_second_half)).astype(np.float32)

def generate_square_half_damped_half(t: np.ndarray, M: int) -> np.ndarray:
    mid_point = M // 2
    t_first_half = t[:mid_point]
    t_second_half = t[mid_point:]
    signal_first_half = SignalGenerators.square_wave(t_first_half)
    signal_second_half = SignalGenerators.damped_oscillation(t_second_half)
    return np.concatenate((signal_first_half, signal_second_half)).astype(np.float32)

def generate_sinus_half_single_half(t: np.ndarray, M: int) -> np.ndarray:
    mid_point = M // 2
    t_first_half = t[:mid_point]
    t_second_half = t[mid_point:]
    signal_first_half = SignalGenerators.sinusoidal(t_first_half)
    signal_second_half = SignalGenerators.single_pulse(t_second_half)
    return np.concatenate((signal_first_half, signal_second_half)).astype(np.float32)

# --- 2. List of new combined signals and their names ---
combined_signal_generators = {
    "Sinus + Square": lambda t_arr: generate_sinus_square(t_arr),
    "Sinus + Chirp": lambda t_arr: generate_sinus_chirp(t_arr),
    "Square + Damped": lambda t_arr: generate_square_damp(t_arr),
    "Sinus[:500] + Square[500:]": lambda t_arr: generate_sinus_half_square_half(t_arr, config.M),
    "Square[:500] + Damped[500:]": lambda t_arr: generate_square_half_damped_half(t_arr, config.M),
    "Sinus[:500] + Single[500:]": lambda t_arr: generate_sinus_half_single_half(t_arr, config.M)
}

# --- 3. Define epsilon values for analysis ---
epsilon_values = [0.01, 0.05, 0.1, 0.3, 0.5, 1.0]

# --- 4. Prepare time array ---
M = config.M
t = np.linspace(0, config.T, M)

# --- 5. Iterate through combined signals, calculate MSE, and plot ---
print("--- Analyzing new combined signals ---")

# Set matplotlib style and font sizes (taking from nt5QTY6mNSXu to ensure consistent style)
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams.update({
    'font.size': 22,
    'axes.titlesize': 20,
    'axes.labelsize': 16,
    'legend.fontsize': 16,
    'xtick.labelsize': 16,
    'ytick.labelsize': 16,
    'figure.titlesize': 22
})

results_table_combined_signals = []

for signal_name, signal_func in combined_signal_generators.items():
    print(f"\n--- Analyzing {signal_name} signal ---\n")

    # Generate the clean combined signal ONCE
    S_clean_combined = signal_func(t).astype(np.float32)

    row_data = {'Signal type': signal_name}

    for eps in epsilon_values:
        print(f"  Evaluating with Epsilon = {eps}...")

        # Add noise to the *same* clean combined signal for current epsilon
        noise = eps * np.random.normal(0, 1, size=M).astype(np.float32)
        Y_noisy_combined = S_clean_combined + noise

        # Predict the reconstructed signal
        predicted_signal_combined = trainer.predict_single(Y_noisy_combined)

        # Calculate MSE
        mse_combined = np.mean((predicted_signal_combined - S_clean_combined)**2)
        print(f"    MSE: {mse_combined:.6f}")
        row_data[f'Epsilon={eps}'] = f'{mse_combined:.6f}'

        # Plotting for each epsilon
        plt.figure(figsize=(14, 7))
        plt.plot(t, Y_noisy_combined, 'r-', alpha=0.7, label='Noisy Signal')
        plt.plot(t, S_clean_combined, 'g--', linewidth=2, label='Original Signal')
        plt.plot(t, predicted_signal_combined, 'b-', linewidth=2, label='Predicted Signal')

        # plt.title(f'Signal Comparison for {signal_name} (\\varepsilon = {eps}, MSE: {mse_combined:.6f})')
        plt.xlabel('Time')
        plt.ylabel('Amplitude')
        plt.legend()
        plt.grid(True, alpha=0.6)
        plt.tight_layout()
        plt.show()

    results_table_combined_signals.append(row_data)

print("\n--- Analysis of all new combined signals completed ---")

df_mse_combined = pd.DataFrame(results_table_combined_signals)

print("\n### MSE Results Table for Combined Signals\n")
print(df_mse_combined.to_markdown(index=False))

plt.figure(figsize=(14, 7))
plt.plot(t_signal, noisy_input, 'r-', alpha=0.7, label='Noisy Signal')
plt.plot(t_signal, signal_clean_resampled, 'g--', linewidth=2, label='Clean Signal (Reference)')
plt.plot(t_signal, predicted_denoised, 'b-', linewidth=2, label='Model Reconstructed Signal')
plt.title(f'Signal Denoising (Epsilon = {noise_eps:.2f})')
plt.xlabel('Time (seconds)')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True, alpha=0.6)
plt.tight_layout()
plt.show()

mse_signal = np.mean((predicted_denoised - signal_clean_resampled)**2)
print(f"\nMSE for signal denoising: {mse_signal:.6f}")

print("\nSignal verification completed.")

import pandas as pd

print("\n--- MSE analysis by epsilon for B007_1_123.mat file ---\n")

# 5 epsilon values
epsilon_values_for_mat = [0.05, 0.1, 0.3, 0.5, 1.0]

results_mat_file_mse = []

# signal_clean_resampled is available from the previous cell
if 'signal_clean_resampled' not in locals():
    print("Error: 'signal_clean_resampled' variable not found. Please run the cell that loads the B007_1_123.mat file first.")
else:
    print(f"Analyzing: B007_1_123.mat signal (epsilon={epsilon_values_for_mat})")
    row_data = {'Signal type': 'B007_1_123.mat'}

    for eps in epsilon_values_for_mat:
        # Add noise to the clean signal at the current epsilon level
        noise = eps * np.random.normal(0, 1, size=config.M).astype(np.float32)
        Y_noisy_mat = signal_clean_resampled + noise

        # Predict the reconstructed signal
        predicted_signal_mat = trainer.predict_single(Y_noisy_mat)

        # Calculate MSE
        mse_mat = np.mean((predicted_signal_mat - signal_clean_resampled)**2)
        row_data[f'Epsilon={eps}'] = f'{mse_mat:.6f}'

    results_mat_file_mse.append(row_data)

    df_mat_file_mse = pd.DataFrame(results_mat_file_mse)

    print("\n--- MSE results table for B007_1_123.mat ---\n")
    print(df_mat_file_mse.to_markdown(index=False))

print("\nB007_1_123.mat analysis completed.")

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# =============================================================================
# 1. Donoho-Johnstone test signal generation functions
# =============================================================================

def blocks(t: np.ndarray) -> np.ndarray:
    """Blocks signal."""
    pos = np.array([.1, .13, .15, .23, .25, .40, .44, .65, .76, .78, .81])
    hgt = np.array([4, -5, 3, -4, 5, -4.2, 2.1, 4.3, -3.1, 2.1, -4.2])
    signal = np.zeros_like(t, dtype=np.float32)
    # Fix: Apply 'h' cumulatively for t >= p to create a step function.
    for p, h in zip(pos, hgt):
        signal[t >= p] += h
    return signal

def bumps(t: np.ndarray) -> np.ndarray:
    """Bumps signal."""
    loc = np.array([.1, .13, .15, .23, .25, .40, .44, .65, .76, .78, .81])
    hgt = np.array([4, 5, 3, 4, 5, 4.2, 2.1, 4.3, 3.1, 5.1, 4.2])
    wth = np.array([.005, .005, .006, .01, .01, .03, .01, .01, .005, .008, .005])
    signal = np.zeros_like(t, dtype=np.float32)
    for l, h, w in zip(loc, hgt, wth):
        signal += h / ((1 + np.abs(t - l) / w)**4)
    return signal

def heavysine(t: np.ndarray) -> np.ndarray:
    """Heavysine signal."""
    return (4 * np.sin(4 * np.pi * t) - np.sign(t - 0.3) - np.sign(0.72 - t)).astype(np.float32)

def doppler(t: np.ndarray) -> np.ndarray:
    """Doppler signal."""
    return np.sqrt(t * (1 - t)) * np.sin(2 * np.pi * (2.1 / (t + 0.05))).astype(np.float32)

# =============================================================================
# 2. Perform the analysis
# =============================================================================

print("\n--- Analyzing Donoho–Johnstone test signals ---")

dj_signals = {
    "Blocks": blocks,
    "Bumps": bumps,
    "Heavysine": heavysine,
    "Doppler": doppler
}

epsilon_values = [0.05, 0.1, 0.3, 0.5, 1.0] # Epsilon values for testing
M = config.M # Signal length
t = np.linspace(0, config.T, M) # Time vector

results_mse = []

# Set matplotlib style and font sizes
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams.update({
    'font.size': 18,
    'axes.titlesize': 20,
    'axes.labelsize': 16,
    'legend.fontsize': 16,
    'xtick.labelsize': 16,
    'ytick.labelsize': 16,
    'figure.titlesize': 22
})

for signal_name, signal_func in dj_signals.items():
    # if signal_name != "Doppler": # Uncomment to only analyze Doppler signal
    #     continue

    print(f"\nSignal type: {signal_name}")
    row_data = {"Signal type": signal_name}

    clean_signal_raw = signal_func(t) # Generate clean signal (original amplitude)
    # The following print statements are for debugging and can be removed for cleaner output
    # print(f"{signal_name} raw signal (first 10): {clean_signal_raw[:10]}")
    # print(f"{signal_name} raw signal (min, max): {clean_signal_raw.min()}, {clean_signal_raw.max()}")

    max_amplitude = np.max(np.abs(clean_signal_raw))
    # print(f"{signal_name} max_amplitude: {max_amplitude}")

    if max_amplitude > 1e-6: # Compare with a small number, avoid division by zero
        clean_signal = clean_signal_raw / max_amplitude # Normalize to [-1, 1]
    else:
        clean_signal = clean_signal_raw # If signal is zero, leave unchanged
    # print(f"{signal_name} normalized signal (first 10): {clean_signal[:10]}")
    # print(f"{signal_name} normalized signal (min, max): {clean_signal.min()}, {clean_signal.max()}")

    for eps in epsilon_values:
        # Add noise
        noise = eps * np.random.normal(0, 1, M).astype(np.float32)
        # Ensure noisy_signal is float32 to avoid dtype mismatch with model
        noisy_signal = (clean_signal + noise).astype(np.float32)

        # Denoise using the model
        predicted_signal = trainer.predict_single(noisy_signal)

        # Calculate MSE
        mse = np.mean((predicted_signal - clean_signal)**2)
        row_data[f'Epsilon={eps}'] = f'{mse:.6f}'
        print(f"  Epsilon={eps:.2f}, MSE={mse:.6f}")

        # Display results in a plot (currently commented out)
        plt.figure(figsize=(14, 7))
        plt.plot(t, noisy_signal, 'r-', alpha=0.7, label='Noisy Signal')
        plt.plot(t, clean_signal, 'g--', linewidth=2, label='Clean Signal')
        plt.plot(t, predicted_signal, 'b-', linewidth=2, label='Model Reconstructed Signal')
        plt.title(f'{signal_name} Signal Denoising (Epsilon = {eps:.2f}, MSE = {mse:.6f})')
        plt.xlabel('Time')
        plt.ylabel('Amplitude')
        plt.legend()
        plt.grid(True, alpha=0.6)
        plt.tight_layout()
        plt.show()

    results_mse.append(row_data)

# Display MSE results in a table
df_dj_mse = pd.DataFrame(results_mse)
print("\n--- MSE results table for Donoho–Johnstone signals ---")
print(df_dj_mse.to_markdown(index=False))

print("\n--- Donoho–Johnstone analysis completed ---")
